#logging.level.root=debug
## Postgresql DB1 - "fdm_db"
#spring.datasource.url=jdbc:postgresql://localhost:5432/technoradar
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://yd-fdmdevdb01.nix.vimpelcom.ru:5432/fdm_db
spring.datasource.username=fdm_user
spring.datasource.password=12fdmuser)(
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
server.port=8086

spring.rabbitmq.template.exchange=adv-exchange
spring.rabbitmq.template.routing-key=adv-routing
spring.rabbitmq.host=rabbit.arch-code.cloud.vimpelcom.ru
spring.rabbitmq.port=5672
spring.rabbitmq.username=dev_user
spring.rabbitmq.password=qwerty
spring.rabbitmq.virtual-host=dev_host

integration.notification-server-url=http://localhost:8082
integration.products-server-url: https://fdm-products-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
