app.version=@project.version@
app.name=@project.name@
spring.mvc.pathmatch.matching-strategy = ant_path_matcher
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
