INSERT INTO techradar.process (name_process, tech_id, created_date)
SELECT v.name_process, v.tech_id, NOW()
FROM (VALUES
          ('zabbix_agent2', 133),
          ('zabbix_proxy', 133),
          ('zabbix-agent2-proxy', 133),
          ('vault', 41),
          ('terraform', 120),
          ('systemd', 4),
          ('ssh-agent', 195),
          ('sshd', 195),
          ('ruby', 173),
          ('redis_exporter', 143),
          ('redis-cli', 143),
          ('redis-sentinel', 143),
          ('redis-server', 143),
          ('rabbitmqctl', 94),
          ('rabbitmq-server', 94),
          ('prometheus', 89),
          ('prometheus-aggr', 89),
          ('prometheus-logs', 89),
          ('prometheus-node', 89),
          ('postgres', 142),
          ('postgres_exporter', 142),
          ('php', 84),
          ('php2db', 84),
          ('php7.4', 84),
          ('php-fpm', 84),
          ('php-fpm5.6', 84),
          ('php-fpm7.4', 84),
          ('php-fpm8.1', 84),
          ('php-fpm81', 84),
          ('ora_arc0_bill', 82),
          ('ora_arc0_billft', 82),
          ('ora_ckpt_bill', 82),
          ('ora_ckpt_billft', 82),
          ('ora_ckpt_billte', 82),
          ('npm run build', 78),
          ('npm run dev --h', 78),
          ('npm run start', 78),
          ('node', 78),
          ('nginx', 77),
          ('nginx-debug', 77),
          ('nginx-ingress-controller', 77),
          ('nginx-prometheus-exporter', 77),
          ('mongod', 141),
          ('mongodb_exporte', 141),
          ('mongosh', 141),
          ('mongodb', 141),
          ('kube-apiserver', 59),
          ('kube-controller', 59),
          ('kubectl', 59),
          ('kubelet', 59),
          ('kube-proxy', 59),
          ('kube-scheduler', 59),
          ('java', 146),
          ('influxdb', 46),
          ('influxd', 46),
          ('haproxy', 149),
          ('haproxy_exporter', 149),
          ('grafana', 39),
          ('grafana-server', 39),
          ('docker', 27),
          ('docker_entrypoint', 27),
          ('dockerd', 27),
          ('clickhouse', 140),
          ('clickhouse_exporter', 140),
          ('apachectl', 7),
          ('httpd', 7),
          ('apache2', 7),
          ('tarantool', 144),
          ('tarantool_is_up', 144),
          ('bm-to-kafka', 56),
          ('kafka_exporter', 56),
          ('kafka-bm-to-gla', 56),
          ('kafkacat', 56),
          ('kafka-comverse-', 56),
          ('kafka-exporter', 56),
          ('kafka-proxy', 56),
          ('kafka-run-class', 56)
     ) AS v(name_process, tech_id)
WHERE EXISTS (SELECT 1 FROM techradar.tech LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM techradar.process LIMIT 1)
  AND EXISTS (SELECT 1 FROM techradar.tech t WHERE t.id = v.tech_id);
