DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM techradar.tech LIMIT 1)
    AND NOT EXISTS (SELECT 1 FROM techradar.process LIMIT 1)
    THEN
        INSERT INTO techradar.process (name_process, tech_id, created_date)
        VALUES
            ('zabbix_agent2', 133, NOW()),
            ('zabbix_proxy', 133, NOW()),
            ('zabbix-agent2-proxy', 133, NOW()),
            ('vault', 41, NOW()),
            ('terraform', 120, NOW()),
            ('systemd', 4, NOW()),
            ('ssh-agent', 195, NOW()),
            ('sshd', 195, NOW()),
            ('ruby', 173, NOW()),
            ('redis_exporter', 143, NOW()),
            ('redis-cli', 143, NOW()),
            ('redis-sentinel', 143, NOW()),
            ('redis-server', 143, NOW()),
            ('rabbitmqctl', 94, NOW()),
            ('rabbitmq-server', 94, NOW()),
            ('prometheus', 89, NOW()),
            ('prometheus-aggr', 89, NOW()),
            ('prometheus-logs', 89, NOW()),
            ('prometheus-node', 89, NOW()),
            ('postgres', 142, NOW()),
            ('postgres_exporter', 142, NOW()),
            ('php', 84, NOW()),
            ('php2db', 84, NOW()),
            ('php7.4', 84, NOW()),
            ('php-fpm', 84, NOW()),
            ('php-fpm5.6', 84, NOW()),
            ('php-fpm7.4', 84, NOW()),
            ('php-fpm8.1', 84, NOW()),
            ('php-fpm81', 84, NOW()),
            ('ora_arc0_bill', 82, NOW()),
            ('ora_arc0_billft', 82, NOW()),
            ('ora_ckpt_bill', 82, NOW()),
            ('ora_ckpt_billft', 82, NOW()),
            ('ora_ckpt_billte', 82, NOW()),
            ('npm run build', 78, NOW()),
            ('npm run dev --h', 78, NOW()),
            ('npm run start', 78, NOW()),
            ('node', 78, NOW()),
            ('nginx', 77, NOW()),
            ('nginx-debug', 77, NOW()),
            ('nginx-ingress-controller', 77, NOW()),
            ('nginx-prometheus-exporter', 77, NOW()),
            ('mongod', 141, NOW()),
            ('mongodb_exporte', 141, NOW()),
            ('mongosh', 141, NOW()),
            ('mongodb', 141, NOW()),
            ('kube-apiserver', 59, NOW()),
            ('kube-controller', 59, NOW()),
            ('kubectl', 59, NOW()),
            ('kubelet', 59, NOW()),
            ('kube-proxy', 59, NOW()),
            ('kube-scheduler', 59, NOW()),
            ('java', 146, NOW()),
            ('influxdb', 46, NOW()),
            ('influxd', 46, NOW()),
            ('haproxy', 149, NOW()),
            ('haproxy_exporter', 149, NOW()),
            ('grafana', 39, NOW()),
            ('grafana-server', 39, NOW()),
            ('docker', 27, NOW()),
            ('docker_entrypoint', 27, NOW()),
            ('dockerd', 27, NOW()),
            ('clickhouse', 140, NOW()),
            ('clickhouse_exporter', 140, NOW()),
            ('apachectl', 7, NOW()),
            ('httpd', 7, NOW()),
            ('apache2', 7, NOW()),
            ('tarantool', 144, NOW()),
            ('tarantool_is_up', 144, NOW()),
            ('bm-to-kafka', 56, NOW()),
            ('kafka_exporter', 56, NOW()),
            ('kafka-bm-to-gla', 56, NOW()),
            ('kafkacat', 56, NOW()),
            ('kafka-comverse-', 56, NOW()),
            ('kafka-exporter', 56, NOW()),
            ('kafka-proxy', 56, NOW()),
            ('kafka-run-class', 56, NOW());
END IF;
END $$;