/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 01-дек-2023 12:40:20 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Category CASCADE
;

DROP TABLE IF EXISTS Ring CASCADE
;

DROP TABLE IF EXISTS Sector CASCADE
;

DROP TABLE IF EXISTS Tech CASCADE
;

DROP TABLE IF EXISTS TechCategory CASCADE
;

/* Create Tables */

CREATE TABLE Category
(
    Id integer NOT NULL,
    name varchar(50) NOT NULL
)
;

CREATE TABLE Ring
(
    Id integer NOT NULL,
    name varchar(50) NOT NULL,
    "order" integer NOT NULL
)
;

CREATE TABLE Sector
(
    id integer NOT NULL,
    name varchar(100) NOT NULL,
    "order" integer NOT NULL
)
;

CREATE TABLE Tech
(
    id integer NOT NULL,
    label varchar(80) NOT NULL,
    description varchar(255) NOT NULL,
    sectorId integer NOT NULL,
    created_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    deleted_date timestamp without time zone NULL,
    link varchar(255) NULL,
    ringId integer NOT NULL
)
;

CREATE TABLE TechCategory
(
    Id integer NOT NULL,
    techId integer NOT NULL,
    categoryId integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Category ADD CONSTRAINT PK_Category
    PRIMARY KEY (Id)
;

ALTER TABLE Ring ADD CONSTRAINT PK_Ring
    PRIMARY KEY (Id)
;

ALTER TABLE Sector ADD CONSTRAINT PK_Sector
    PRIMARY KEY (id)
;

ALTER TABLE Tech ADD CONSTRAINT PK_Capability
    PRIMARY KEY (id)
;

CREATE INDEX IXFK_Tech_Ring ON Tech (ringId ASC)
;

CREATE INDEX IXFK_Tech_Sector ON Tech (sectorId ASC)
;

ALTER TABLE TechCategory ADD CONSTRAINT PK_TechCategory
    PRIMARY KEY (Id)
;

CREATE INDEX IXFK_TechCategory_Category ON TechCategory (categoryId ASC)
;

CREATE INDEX IXFK_TechCategory_Tech ON TechCategory (techId ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Tech ADD CONSTRAINT FK_Tech_Ring
    FOREIGN KEY (ringId) REFERENCES Ring (Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Tech ADD CONSTRAINT FK_Tech_Sector
    FOREIGN KEY (sectorId) REFERENCES Sector (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE TechCategory ADD CONSTRAINT FK_TechCategory_Category
    FOREIGN KEY (categoryId) REFERENCES Category (Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE TechCategory ADD CONSTRAINT FK_TechCategory_Tech
    FOREIGN KEY (techId) REFERENCES Tech (id) ON DELETE No Action ON UPDATE No Action
;
