UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/RfVsFg', last_modified_date = CURRENT_DATE where label = 'Ansible';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/TPVsFg', last_modified_date = CURRENT_DATE where label = 'argoCD';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/KPVsFg', last_modified_date = CURRENT_DATE where label = 'Docker';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/L-VsFg', last_modified_date = CURRENT_DATE where label = 'GitLab CE';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/KvVsFg', last_modified_date = CURRENT_DATE where label = 'Harbor';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/J-VsFg', last_modified_date = CURRENT_DATE where label = 'HashiCorp Vault';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/SvVsFg', last_modified_date = CURRENT_DATE where label = 'Helm';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/LPVsFg', last_modified_date = CURRENT_DATE where label = 'Jenkins';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/RvVsFg', last_modified_date = CURRENT_DATE where label = 'Terraform';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/OfVsFg', last_modified_date = CURRENT_DATE where label = 'Alpine Linux';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/N-VsFg', last_modified_date = CURRENT_DATE where label = 'Rocky Linux 8.5';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/M-VsFg', last_modified_date = CURRENT_DATE where label = 'Ubuntu 20.04 22.04';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/NfVsFg', last_modified_date = CURRENT_DATE where label = 'CentOS';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/NvVsFg', last_modified_date = CURRENT_DATE where label = 'Oracle Linux';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/N-VsFg', last_modified_date = CURRENT_DATE where label = 'Rocky Linux <8.5';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/M-VsFg', last_modified_date = CURRENT_DATE where label = 'Ubuntu < 20.04 22.04';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/SPVsFg', last_modified_date = CURRENT_DATE where label = 'NSM (BMC)';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/T-VsFg', last_modified_date = CURRENT_DATE where label = 'Remedy BMC';
UPDATE techradar.tech set link='https://bwiki.beeline.ru/x/TvVsFg', last_modified_date = CURRENT_DATE where label = 'TTMS';
