UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Ansible';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'argoCD';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Docker';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'GitLab CE';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Harbor';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'HashiCorp Vault';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Helm';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Jenkins';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Terraform';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Alpine Linux';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Rocky Linux 8.5';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Ubuntu 20.04 22.04';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'CentOS';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Oracle Linux';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Rocky Linux <8.5';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Ubuntu < 20.04 22.04';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'NSM (BMC)';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'Remedy BMC';
UPDATE techradar.tech set link='https://example.com', last_modified_date = CURRENT_DATE where label = 'TTMS';
