/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 05-ноя-2024 15:46:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_black_list_id
;

DROP SEQUENCE IF EXISTS seq_tech_bl_product_id
;

/* Drop Tables */

DROP TABLE IF EXISTS black_list CASCADE
;

DROP TABLE IF EXISTS tech_bl_product CASCADE
;

/* Create Tables */

CREATE TABLE black_list
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_black_list_id'::text)::regclass),
    label varchar(80) NOT NULL,
    review boolean NOT NULL,
    create_date timestamp without time zone NOT NULL,
    delete_date timestamp without time zone NULL
)
;

CREATE TABLE tech_bl_product
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_tech_bl_product_id'::text)::regclass),
    cmdb_code varchar(80) NOT NULL,
    tech_bl_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE black_list ADD CONSTRAINT pk_black_list
    PRIMARY KEY (id)
;

ALTER TABLE tech_bl_product ADD CONSTRAINT pk_tech_bl_product
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_tech_bl_product_black_list ON tech_bl_product (tech_bl_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE tech_bl_product ADD CONSTRAINT fk_tech_bl_product_black_list
    FOREIGN KEY (tech_bl_id) REFERENCES black_list (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq_black_list_id INCREMENT 1 START 1
;

CREATE SEQUENCE seq_tech_bl_product_id INCREMENT 1 START 1
;
