-- Вставляем записи в таблицу black_list
INSERT INTO techradar.black_list (id, label, review, create_date)
VALUES
    (nextval('seq_black_list_id'), 'Dockerfile', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Shell', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'HTML', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'CSS', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Batchfile', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'SCSS', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Smarty', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Makefile', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PowerShell', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'TSX', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PLpgSQL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'TSQL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'ASL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Mustache', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PLSQL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'HTML+Razor', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'XSLT', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Roff', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PostCSS', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'ASP.NET', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Gherkin', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Mako', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Less', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Pug', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Roff Manpage', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'FreeMarker', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Rich Text Format', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'CMake', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Fluent', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Jupyter Notebook', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Handlebars', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'EJS', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Hack', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Raku', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Motorola 68K Assembly', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Assembly', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'M4', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'VBScript', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Procfile', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Yacc', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Vim Script', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'F#', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Tcl', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'NASL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Twig', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'ANTLR', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Tcsh', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Clojure', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Dart', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'SQLPL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'D', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Cuda', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'TeX', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Ragel', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Thrift', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Stylus', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Pawn', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PostScript', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Cython', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Starlark', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PureBasic', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Prolog', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Ada', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Sass', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'VBA', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Liquid', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Svelte', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Jsonnet', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'HiveQL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'BlitzBasic', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'MATLAB', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Cypher', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Pan', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Vim Snippet', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'YARA', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Fortran', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'GAP', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'HTML+PHP', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Julia', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Unix Assembly', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Visual Basic 6.0', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Inno Setup', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'BitBake', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Meson', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Module Management System', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Awk', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Mathematica', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'QMake', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'ActionScript', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Elm', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Erlang', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Limbo', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Nim', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'XS', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Blade', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'M4Sugar', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'CoffeeScript', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'VCL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'AMPL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'PowerBuilder', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'SourcePawn', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'COBOL', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'QML', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'Visual Basic .NET', true, CURRENT_TIMESTAMP),
    (nextval('seq_black_list_id'), 'xBase', true, CURRENT_TIMESTAMP);