/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 16-дек-2024 10:47:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_tech_version
;

/* Drop Tables */

DROP TABLE IF EXISTS techradar.tech_version CASCADE
;

/* Create Tables */

CREATE TABLE techradar.tech_version
(
    id integer NOT NULL   DEFAULT NEXTVAL(('seq_tech_version'::text)::regclass),
    version_start varchar(50) NULL,
    version_end varchar(50) NULL,
    status_id integer NOT NULL,
    created_date timestamp without time zone NOT NULL,
    deleted_date timestamp without time zone NULL,
    last_modified_date timestamp without time zone NULL,
    tech_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE techradar.tech_version ADD CONSTRAINT pk_tech_version
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_tech_version_ring ON techradar.tech_version (status_id ASC)
;

CREATE INDEX ixfk_tech_version_tech ON techradar.tech_version (tech_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE techradar.tech_version ADD CONSTRAINT fk_tech_version_ring
    FOREIGN KEY (status_id) REFERENCES ring (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE techradar.tech_version ADD CONSTRAINT fk_tech_version_tech
    FOREIGN KEY (tech_id) REFERENCES tech (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq_tech_version INCREMENT 1 START 1
;
